### PR TITLE
Create uploadfiles.io.json

### PR DESCRIPTION
**Pull request by FractalWire**

### CODE REVIEW

**Comment by Jaex** [comment]
http://uploadfiles.io not opens.

**Comment by FractalWire** [comment]
not opens as in close source ?

**Comment by FractalWire** [comment]
weird, it's working fine for me :

**Comment by Jaex** [comment]
It only opens with VPN for me which means you blocking my normal ip.

**Comment by FractalWire** [comment]
note that I'm not the owner of this site.
If that's not indiscret, where are you located on the planet ?
I'll send them a notice for that problem.

**Comment by Jaex** [comment]
Turkey.

**Comment by ryanbadger** [comment]
I believe uploadfiles.io is blocked in Turkey... they seem rather strict on file sharing services

**Comment by FractalWire** [comment]
Indeed it looks like Turkey is blocking uploadfiles.io
They also blocked dropbox, onedrive, and apparently Github a few weeks back. And it looks like there was an important shutdown yesterday https://turkeyblocks.org/2016/10/27/new-internet-shutdown-turkey-southeast-offline-diyarbakir-unrest/

**Comment by Jaex** [comment]
Blocks of Dropbox, OneDrive etc. opened so it is not proof that Turkey blocked uploadfiles too.

**Comment by FractalWire** [comment]
Well, after contacting uploadfiles, they seems to think they are blocked by turkey:



Dropbox, OneDrive, etc. are the only mention I found on the internet but that's also the more popular.

Is uploadfiles.io the only file sharing service that fail for you ?

**Comment by Jaex** [comment]
Dropbox, OneDrive blocks opened two days later so it is not same thing. Yes I don't know any other file sharing service which not opens currently.

**Pull request merged**
