### PR TITLE
Remove boring.host

### PR DESCRIPTION
**Pull request by iraizo**
The API dosent respond since days

### CODE REVIEW

**Comment by iraizo** [comment]
Also added dog.bin

**Comment by iraizo** [comment]
@Jaex Is this right?

**Comment by iraizo** [comment]
@Jaex ?

**Comment by KeepSOBP** [comment]
I think dogbin file had problem
https://github.com/ShareX/CustomUploaders/blob/master/.github/CONTRIBUTING.md
dog.bin (Text Uploader, URL shortener).sxcu -> del.dog (Text Uploader, URL shortener).sxcu
Maybe change name to del.dog to possible merge it

**Comment by iraizo** [comment]
> 
> 
> I think dogbin file had problem
> https://github.com/ShareX/CustomUploaders/blob/master/.github/CONTRIBUTING.md
> 
> Maybe change name to del.dog to possible merge it

The file itself is named ` dog.bin (Text Uploader, URL shortener).sxcu ` How would i correct it?

**Comment by KeepSOBP** [comment]
> > I think dogbin file had problem
> > https://github.com/ShareX/CustomUploaders/blob/master/.github/CONTRIBUTING.md
> > Maybe change name to del.dog to possible merge it
> 
> The file itself is named `dog.bin (Text Uploader, URL shortener).sxcu` How would i correct it?



just rename it

**Comment by iraizo** [comment]
> 
> 
> > > I think dogbin file had problem
> > > https://github.com/ShareX/CustomUploaders/blob/master/.github/CONTRIBUTING.md
> > > Maybe change name to del.dog to possible merge it
> > 
> > 
> > The file itself is named `dog.bin (Text Uploader, URL shortener).sxcu` How would i correct it?
> 
> 
> just rename it

oh shoot the domain is something else ur right

**Comment by iraizo** [comment]
@Jaex Should be fine to merge now

**Comment by KeepSOBP** [comment]
Screenshot_20201007-075651_Chrome

And... maybe division this service too?

idk wait a while and if he doesn't merging this, try it

**Comment by iraizo** [comment]
Will do!

**Pull request closed without merging**
