### PR TITLE
Endpoint change for owo.whats-th.is, and awau.moe URL shortener

### PR DESCRIPTION
**Pull request by aurieh**

### CODE REVIEW

**Comment by Jaex** [comment]
ShareX supports Polr url shorteners:

**Comment by aurieh** [comment]
Polr shortener support is for services that don't need authentication. Our service needs an API key.
You stated before, that you accepted pomf endpoint of owo just because it had authentication..
Anyways, if you really don't want to merge this, I can open a PR for endpoint change (for file uploader), since current json file is broken.

**Comment by Jaex** [comment]
In my screenshot there is "API key" text box.

**Comment by martmists** [comment]
time to uninstall sharex if the devs really are like this, rejecting input from users.

**Comment by martmists** [comment]
We don't, we (or at least I do) thoroughly read your responses, and talk it over between us.

**Comment by Jaex** [comment]
What input am I rejected can you tell me?

**Comment by aurieh** [comment]
I'm 99% sure API key option sends a polr request with query arg name as `api_key`. We only accept `key`.
If it does send `key`, I will be glad to make a PR just updating file upload endpoint, nothing else.

**Comment by Jaex** [comment]
Are they changed their API to use "key" parameter or you customized API yourself? If they did change in API then ShareX Polr support must be updated to support latest changes. Instead of adding custom uploader to workaround this issue.

**Comment by martmists** [comment]
As far as I know polr still uses `api_key`, which is exactly why I made #61

**Comment by aurieh** [comment]
@Jaex Our API is not exactly polr, it just uses a similar method. polr.me still uses apikey (or api_key), but we use just `key`. Thats exactly why @martmists opened a PR.

**Comment by Jaex** [comment]
ShareX uses `apikey` currently but http://docs.polr.me/en/latest/developer-guide/api/#api-keys page tells `key` so that means they must be changed it in API and I must change it in ShareX to have latest API support. I will go to their IRC channel and ask about it.

**Comment by Jaex** [comment]
Look like they released API 2.0 which using `key` argument now. And ShareX was using API 1.0. I will support 2.0 by default and have optional setting to still support 1.0 version. Your polr endpoint is API 2.0 compatible I think.

**Comment by Jaex** [comment]
Added Polr API v2 support which gonna be used by default: https://github.com/ShareX/ShareX/commit/8aa7f4ea6d819405e36f7e666c562dc73eb2e995

**Pull request closed without merging**
