### PR TITLE
Add an Imgbb uploader config.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Noticed this one wasn't on here:
https://imgbb.com/

It's a great image upload site with good privacy settings.

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@Jaex, does this look valid?

**Comment by Jaex** [comment]
No.

**Comment by ryanpcmcquen** [comment]
@Jaex, which part is invalid?

**Comment by KeepSOBP** [comment]
You need this in response - URL $json:data.url$

**Comment by ryanpcmcquen** [comment]
@KeepSOBP, thank you! I added the url, thumbnail url, and deletion url. @Jaex, is this looking better?

**Comment by ryanpcmcquen** [comment]
This should be ready to merge.

**Comment by ryanpcmcquen** [comment]
This is ready to go.

**Comment by KeepSOBP** [comment]
@ryanpcmcquen

**Comment by ryanpcmcquen** [comment]
I will update.

**Comment by ryanpcmcquen** [comment]
@Jaex this had been updated.

**Comment by ryanpcmcquen** [comment]
Sorry about that, I followed the format of some old ones here and should have checked the contributing doc first.

**Pull request merged**
