### PR TITLE
Add 0x0f.su.sxcu

### PR DESCRIPTION
**Pull request by k0nsl**
Add domain https://0x0f.su

### CODE REVIEW

**Comment by Jaex** [comment]
You should set `DestinationType` for easy import.

**Comment by k0nsl** [comment]
@Jaex: I just followed the general syntax for already added custom uploaders and they were all set to `None`.

**Comment by Jaex** [comment]
There was no `DestinationType` option when those custom uploaders added.

**Comment by k0nsl** [comment]
Aha, I see. Well, I've populated `DestinationType` now.

**Pull request merged**
