### PR TITLE
Add ipfs.io.sxcu

### PR DESCRIPTION
**Pull request by marcin212**

### CODE REVIEW

**Comment by Jaex** [comment]
There is space in beginning of URL field.

**Comment by Bluscream** [comment]
`"RequestURL": "http://localhost:5001/api/v0/add"` OwO whats that on localhost?

**Comment by magik6k** [comment]
This is the default address or the IPFS daemon(see https://ipfs.io/). IPFS is a p2p decentralized filesystem addressed by file hash. `ipfs.io/ipfs/` is a public ipfs gateway provided by Protocol Labs (the company backing IPFS). It could also be `localhost:8080/ipfs`, but as not everyone is running an ipfs node, using `ipfs.io` is the way to access, for most people running local node this is still fine as there are browser plugins that redirect `ipfs.io` to a local gateway.

**Comment by Bluscream** [comment]
Ahh i thought it was some pomf like uploader. nvm then ^~^

**Pull request merged**
