### PR TITLE
Added gofile.io

### PR DESCRIPTION
**Pull request by master4x**
I've writed this Upload script for version 13.2.1 of ShareX

### CODE REVIEW

**Comment by Jaex** [comment]
That parameter is not used because you already set file at bottom.

**Comment by master4x** [comment]
Please tell me which one to fix.

**Review by KeepSOBP — CHANGES_REQUESTED** [review]
You don't need to add URL parameter.
Delete url parameter and test it

**Comment by master4x** [comment]
Thanks for the information.
I've edited it so you can pull it now.

**Pull request merged**
