### PR TITLE
added beeimg.com

### PR DESCRIPTION
**Pull request by miyurusankalpa**
added BeeIMG custom image uploader

### CODE REVIEW

**Comment by Jaex** [comment]
Check https://github.com/ShareX/CustomUploaders#rules for naming to be consistent with others.

**Comment by miyurusankalpa** [comment]
fixed the name. thought only file name should be consistent.

**Comment by Jaex** [comment]
What then if there is two Pastebin one is pastebin.com other is pastebin.ca in custom uploader list both will have same name... Are you thinking I decided on that naming for no reason?

**Comment by miyurusankalpa** [comment]
I get it. In the readme it reads "**name and file name**" and have examples to the json files. It was my mistake by not reading the readme thoroughly. sorry.

**Pull request merged**
