### PR TITLE
Create mediauploadnet.sxcu

### PR DESCRIPTION
**Pull request by KeksKartoffel**

### CODE REVIEW

**Comment by ShahadatRD** [comment]
Are you using user secret api ? isn't that like things are getting stored under someone's account?

**Comment by KeksKartoffel** [comment]
No, because the upload should not be assigned to any users.

**Comment by KeksKartoffel** [comment]
Yes and no.
It should be possible that the user can upload anonymously and (if he has an account) upload to an account (with secret key). Then that was probably my error in the file.

**Comment by ShahadatRD** [comment]
Well, uploading anonymously is safe in that case as this ain't a private application.

**Comment by KeksKartoffel** [comment]
I changed the secret key in the file to "<your key goes here>". That should fit, right?

**Comment by KeksKartoffel** [comment]
Update?

**Pull request closed without merging**
