### PR TITLE
Add owo.whats-th.is URL shortener

### PR DESCRIPTION
**Pull request by martmists**
Actual domain is uwu.whats-th.is but it's both the same

### CODE REVIEW

**Comment by Jaex** [comment]
ShareX supports Polr url shorteners:

**Comment by martmists** [comment]
Then why did the original owo get accepted again because that was literally a pomf endpoint

Anyways, I already have polr set up and I don't really want to have to keep switching between the two if I want a specific one

Thought like maybe others felt the same way

**Comment by Jaex** [comment]
It was not literally pomf endpoint. It was requiring api key which is major difference.

**Comment by martmists** [comment]
The api key is to be put in the URL, which makes it no different from a pomf endpoint as it would just work with the default pomf uploader.

**Comment by aurieh** [comment]
One of awau.moe/uwu.whats-th.is devs here, api key IS required as either
A. `authorization` header
B. `?key=` query param

**Comment by Jaex** [comment]
Nobody expects api key when they select pomf destination because default pomf implementation not supports api keys. So when user select that destination he won't have any idea why uploader not works. So it is not same.

**Comment by eye-sigil** [comment]
please read aurieh's comment, they got it explained down pat ^

**Comment by martmists** [comment]
Both endpoints require authorization as Aurieh said, You're saying only one does? 🤔

**Comment by aurieh** [comment]
We literally have router middleware for authentication, on every single endpoint, except serving of files, cloudfront CDN takes care of that.

**Comment by martmists** [comment]
Nice, now it won't work 👍

**Pull request closed without merging**
