### PR TITLE
Add pixeldrain.com uploader

### PR DESCRIPTION
**Pull request by Fornax96**
I'm the creator of pixeldrain.com, a file sharing website with over a hundred thousand unique monthly visitors. Pixeldrain supports online previews for images, videos, audio, text and PDF documents.

Please consider adding this uploader to the main ShareX project too. I'll create a page on pixeldrain.com recommending ShareX as an officially supported desktop client.

### CODE REVIEW

**Comment by Jaex** [comment]
Malwarebytes blocking your web site.

**Comment by Fornax96** [comment]
Hmm, that's odd. I haven't received any virus reports for three months. I'll send them an e-mail.

**Comment by Fornax96** [comment]
Thanks!

**Comment by Fornax96** [comment]
Malwarebytes support says they have removed the block.

**Pull request merged**
