### PR TITLE
Finnish Pomf clone Filuboksi.fi support

### PR DESCRIPTION
**Pull request by nnaricom**

### CODE REVIEW

**Comment by nnaricom** [comment]
I guess there's no need to change the destination type since it's a pomf clone and other CustomUploaders are using `None` as the `DestinationType` aswell.

**Comment by Jaex** [comment]
When other custom uploaders added there were no DestinationType support. It is not even possible to export .sxcu file without configure DestinationType in latest ShareX version.

**Comment by nnaricom** [comment]
Well you can upload basically anything, what should I define it as?

**Pull request merged**
