### PR TITLE
[Urlify.dev] Added New URL Short Service 

### PR DESCRIPTION
**Pull request by varunsridharan**
https://urlify.dev is a free URL shortener which is secure & Anonymous with 0 logs. and also provides a quickly accessable API to create Short URL on the fly

https://www.producthunt.com/posts/urlify-secure-anonymous

### CODE REVIEW

**Comment by Jaex** [comment]
Why body is "JSON" if there is no body in request?

**Comment by varunsridharan** [comment]
`https://urlify.dev/api/?url=google.com&method=json` return a proper json string

**Comment by Jaex** [comment]
Request body is unrelated to request response.

**Comment by varunsridharan** [comment]
@Jaex i am new to this. if you could explain i would change it based on that

**Comment by Jaex** [comment]
Removed body section.

**Comment by varunsridharan** [comment]
@Jaex thanks i will keep in mind and make sure this never happens again

**Pull request merged**
