### PR TITLE
New customer uploader: catgirlsare.sexy

### PR DESCRIPTION
**Pull request by Xalaxis**
Is this acceptable?  It should be noted that the default pomf config no longer works with the layout catgirlsare.sexy uses it seems.

### CODE REVIEW

**Comment by Jaex** [comment]
It is same as https://github.com/ShareX/CustomUploaders/blob/master/sr.ht.json isn't it?
Then why your URL have 2x dot

**Comment by Xalaxis** [comment]
Woops, sorry, that must have been from when I was experimenting with deepscan vs. raw child nodes.  Let me just remove that

**Comment by Xalaxis** [comment]
Give me a second to check this works

**Comment by Jaex** [comment]
Why yours have 1x dot? In my script there is no need dot.

**Comment by Xalaxis** [comment]
Yeah, that should work fine. Sorry.

**Pull request merged**
