### PR TITLE
Delete ratelimited.me.sxcu

### PR DESCRIPTION
**Pull request by popey456963**
ETIMEDOUT

### CODE REVIEW

**Comment by gtsatsis** [comment]
Hi there,

I'm the lead developer of RATELIMITED. It's up and running just fine, and the API works just fine, it's a you issue (See below, can't attach images on mobile)

Motion to close w/o merging.

**Comment by gtsatsis** [comment]
Screenshot_20191226-162306_Chrome

**Comment by gtsatsis** [comment]
It appears that our Opsgenie pagers had been going off at the time of this PR being created, meaning that something had gone wrong.

I see that you created multiple PRs in regards to multiple services, I'd suggest running multiple checks across multiple days before submitting, as to avoid the deletion of still-active services.

Screenshot below:
Screenshot_20191226-162710_Opsgenie

**Comment by popey456963** [comment]
My apologies, will close.

**Pull request closed without merging**
